name: Docker сборка и запуск

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      actions: write
      
    steps:
    - name: Проверка кода
      uses: actions/checkout@v4  # Обновленная версия

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Сборка образа Docker
      run: |
        docker build -t hw08-app .
        docker tag hw08-app ghcr.io/${{ github.repository_owner }}/hw08-app:latest

    - name: Пуш образа Docker
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/hw08-app:latest

    - name: Запуск контейнера и получение логов
      run: |
        mkdir -p logs
        docker run \
          --mount type=bind,source=$(pwd)/logs,target=/output \
          hw08-app
        
        # Проверка наличия логов
        if [ ! -f logs/log.txt ]; then
          echo "Log file not found!"
          exit 1
        fi

    - name: Загрузка logs artifact
      uses: actions/upload-artifact@v4  # Обновленная версия
      with:
        name: build-logs
        path: logs/log.txt
        retention-days: 5