name: Docker Build and Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner.lower() }}/hw08-app

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Установка Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Сборка и пуш
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Запуск контейнера
      run: |
        mkdir -p logs
        docker run \
          --name hw08-container \
          -v $(pwd)/logs:/output \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} || echo "Container run completed"
        
        ls -la logs/
        [ -f logs/log.txt ] && cat logs/log.txt || docker logs hw08-container

    - name: Выгрузка logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/log.txt
        if-no-files-found: warn