name: Docker Build and Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/hw08-app
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Run container and save logs
      run: |
        mkdir -p logs
        docker run \
          --name hw08-container \
          -v $(pwd)/logs:/output \
          ghcr.io/${{ github.repository_owner }}/hw08-app || true
        
        # Проверяем наличие логов
        if [ -f logs/log.txt ]; then
          echo "Logs saved successfully"
          cat logs/log.txt
        else
          echo "Error: No log file found!"
          docker logs hw08-container > logs/container_logs.txt 2>&1
          exit 1
        fi

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: app-logs
        path: logs/log.txt
        if-no-files-found: error