name: Docker Pipeline

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t hw08-app .

    - name: Run container
      run: |
        mkdir -p logs
        docker run -v $(pwd)/logs:/output hw08-app

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: logs/log.txt